### ISSUE TITLE
Black Card Text not displaying

### ISSUE THREAD

**Issue by kthornsbury** [amirrajan/nodejs-against-humanity#23]
This app is an excellent example. I've been using it to better understand node and angular, so great job! When I first started it, I noticed that my black cards weren't displaying as I was playing the game. On line 11 of the views/game.html file I noticed that the ng-bind-html read "game.currentBlackCard" instead of "game.currentBlackCard.text". I'm not sure if anyone else was having this issue (or if it was browser specific). Thanks!

**Comment by amirrajan** [comment]
I'll take a look. I merged in a pull request a few days ago that might have broken it. cc @kaiserfro

**Comment by kaiserfro** [comment]
I don't seem to have a problem with this...the ng-bind-html is correct as far as I can tell, since the code inside game.js:setCurrentBlackCard() uses game.deck.black[index].text already, so the bound attribute within the html should be the text already.

Maybe there is a specific card that is not rendering?

**Comment by amirrajan** [comment]
Should be able to take a look this weekend.

**Comment by jschnarr** [comment]
kaiserfro I synced to your branch and that fixed it. I didn't isolate the problematic diff.

**Comment by amirrajan** [comment]
Can I close this issues @jschnarr ?

**Comment by kaiserfro** [comment]
It is indeed broken.  I finally diffed my repo with the current master, and there is one line missing from the current master that would cause this problem.

I'll create a PR.
